# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "win" ]
  pull_request:
    branches: [ "win" ]
  workflow_dispatch: 

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Get project dependencies
      run: go mod download
      
    - name: Build
      run: sh ./build.sh -p win
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SingBox
        path: SingBox.exe
